<a href="https://colab.research.google.com/github/as5492/AICC/blob/main/exp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ***TOWER OF HANOI***

In [ ]:
def TowerOfHanoi(n , s_pole, d_pole, i_pole):
    if n == 1:
        print("Move disc 1 from pole",s_pole,"to pole",d_pole)
        return
    TowerOfHanoi(n-1, s_pole, i_pole, d_pole)
    print("Move disc",n,"from pole",s_pole,"to pole",d_pole)
    TowerOfHanoi(n-1, i_pole, d_pole, s_pole)

n = 3
TowerOfHanoi(n, 'A', 'C', 'B')

Move disc 1 from pole A to pole C
Move disc 2 from pole A to pole B
Move disc 1 from pole C to pole B
Move disc 3 from pole A to pole C
Move disc 1 from pole B to pole A
Move disc 2 from pole B to pole C
Move disc 1 from pole A to pole C


### ***4 N-QUEENS***

In [ ]:
N = 4
ld = [0] * 30
rd = [0] * 30
cl = [0] * 30
def printSolution(board):
    for i in range(N):
        for j in range(N):
            print(" Q " if board[i][j] == 1 else " . ", end="")
        print()
def solveNQUtil(board, col):
    if col >= N:
        return True
    for i in range(N):
        if (ld[i - col + N - 1] != 1 and rd[i + col] != 1) and cl[i] != 1:
            board[i][col] = 1
            ld[i - col + N - 1] = rd[i + col] = cl[i] = 1
            if solveNQUtil(board, col + 1):
                return True
            board[i][col] = 0  # BACKTRACK
            ld[i - col + N - 1] = rd[i + col] = cl[i] = 0
    return False
def solveNQ():
    board = [[0 for _ in range(N)] for _ in range(N)]
    if not solveNQUtil(board, 0):
        print("Solution does not exist")
        return False
    printSolution(board)
    return True
if __name__ == "__main__":
    solveNQ()

 .  .  Q  . 
 Q  .  .  . 
 .  .  .  Q 
 .  Q  .  . 


### ***TIC TAC TOE***

In [ ]:
import numpy as np
import random
from time import sleep
def create_board():
    return(np.array([[0, 0, 0],
                     [0, 0, 0],
                     [0, 0, 0]]))
def possibilities(board):
    l = []

    for i in range(len(board)):
        for j in range(len(board)):

            if board[i][j] == 0:
                l.append((i, j))
    return(l)
def random_place(board, player):
    selection = possibilities(board)
    current_loc = random.choice(selection)
    board[current_loc] = player
    return(board)
def row_win(board, player):
    for x in range(len(board)):
        win = True

        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                continue

        if win == True:
            return(win)
    return(win)
def col_win(board, player):
    for x in range(len(board)):
        win = True

        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                continue

        if win == True:
            return(win)
    return(win)
def diag_win(board, player):
    win = True
    y = 0
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
    if win:
        return win
    win = True
    if win:
        for x in range(len(board)):
            y = len(board) - 1 - x
            if board[x, y] != player:
                win = False
    return win
def evaluate(board):
    winner = 0

    for player in [1, 2]:
        if (row_win(board, player) or
                col_win(board, player) or
                diag_win(board, player)):

            winner = player

    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner
def play_game():
    board, winner, counter = create_board(), 0, 1
    print(board)
    sleep(2)

    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print("Board after " + str(counter) + " move")
            print(board)
            sleep(2)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break
    return(winner)
print("Winner is: " + str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 1 0]
 [0 0 0]]
Board after 2 move
[[0 2 0]
 [0 1 0]
 [0 0 0]]
Board after 3 move
[[0 2 1]
 [0 1 0]
 [0 0 0]]
Board after 4 move
[[0 2 1]
 [0 1 0]
 [0 0 2]]
Board after 5 move
[[0 2 1]
 [0 1 1]
 [0 0 2]]
Board after 6 move
[[0 2 1]
 [0 1 1]
 [2 0 2]]
Board after 7 move
[[0 2 1]
 [0 1 1]
 [2 1 2]]
Board after 8 move
[[2 2 1]
 [0 1 1]
 [2 1 2]]
Board after 9 move
[[2 2 1]
 [1 1 1]
 [2 1 2]]
Winner is: 1
